version: '3.8'

services:
  nginx:
    container_name: nginx
    image: traumereidev/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl/cert.pem:/etc/ssl/cert.pem
      - ./nginx/ssl/privkey.pem:/etc/ssl/privkey.pem
    depends_on:
      - backend

  backend:
    container_name: backend
    image: traumereidev/backend:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./postgre/dump.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  dbdata:
