version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/cert.pem:/etc/ssl/cert.pem
      - ./nginx/ssl/privkey.pem:/etc/ssl/privkey.pem
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydb
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - ./postgre/dump.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  postgres_data:
