name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build backend image
        run: docker build -t backend:latest ./backend

      - name: Build nginx image
        run: docker build -t nginx:latest ./nginx

      - name: Login to Docker registry (если нужно)
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Save backend image to tar
        run: docker save backend:latest -o backend.tar

      - name: Save nginx image to tar
        run: docker save nginx:latest -o nginx.tar

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: |
            backend.tar
            nginx.tar
            docker-compose.yml
            ansible/
          target: /home/${{ secrets.VPS_USER }}/deploy/

      - name: Connect to VPS and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VPS_USER }}/deploy
            docker load -i backend.tar
            docker load -i nginx.tar
            docker-compose down
            docker-compose up -d --build
