name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push images
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/backend:latest ./backend
          docker build -t ${{secrets.DOCKER_USERNAME}}/nginx:latest ./nginx
          docker push ${{secrets.DOCKER_USERNAME}}/nginx:latest
          docker push ${{secrets.DOCKER_USERNAME}}/backend:latest


      - name: Connect to VPS and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /opt/webapp
            git pull origin main
            docker pull ${{secrets.DOCKER_USERNAME}}/nginx:latest
            docker pull ${{secrets.DOCKER_USERNAME}}/backend:latest
            docker-compose down
            docker-compose up -d
